#!/usr/bin/env python3

from __future__ import annotations

import pathlib
import re
import sys


def extract_target_block(text: str, target: str) -> str | None:
    marker = f"    {target} = {{"
    start = text.find(marker)
    if start < 0:
        return None

    index = start + len(marker)
    depth = 1
    while index < len(text):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start + len(marker):index]
        index += 1
    return None


def extract_bmi_by_source(block: str, sourcefile: str) -> str | None:
    pattern = re.compile(
        rf"\n\s*\[\"{re.escape(sourcefile)}\"\] = \{{.*?\n\s*bmifile = \"([^\"]+)\"",
        re.DOTALL,
    )
    match = pattern.search(block)
    return match.group(1) if match else None


def main() -> int:
    repo_root = pathlib.Path(__file__).resolve().parent.parent
    cache_path = repo_root / ".xmake" / "linux" / "x86_64" / "cache" / "cxxmodules"
    if not cache_path.is_file():
        print(f"clangd module sync skipped: missing {cache_path}", file=sys.stderr)
        return 0

    block = extract_target_block(cache_path.read_text(encoding="utf-8"), "su_app")
    if not block:
        print("clangd module sync skipped: target su_app not found in cxxmodules cache", file=sys.stderr)
        return 0

    std_bmi = extract_bmi_by_source(block, "/usr/share/libc++/v1/std.cppm")
    std_compat_bmi = extract_bmi_by_source(block, "/usr/share/libc++/v1/std.compat.cppm")
    if not std_bmi or not std_compat_bmi:
        print("clangd module sync skipped: std/std.compat BMI paths not found", file=sys.stderr)
        return 0

    std_bmi_path = (repo_root / std_bmi).resolve()
    std_compat_bmi_path = (repo_root / std_compat_bmi).resolve()
    prebuilt_dir = std_bmi_path.parent

    clangd_path = repo_root / ".clangd"
    clangd_path.write_text(
        "\n".join(
            [
                "# Generated by tools/sync_clangd_modules.py",
                "# Re-run `xmake` to refresh when module cache paths change.",
                "CompileFlags:",
                "  Add:",
                "    - -stdlib=libc++",
                f"    - -fprebuilt-module-path={prebuilt_dir}",
                f"    - -fmodule-file=std={std_bmi_path}",
                f"    - -fmodule-file=std.compat={std_compat_bmi_path}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(f"updated {clangd_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
